### ISSUE TITLE
Request to add the script for ROC-AUC curve calculation

### ISSUE THREAD

**Issue by Sowmya-R-Krishnan** [dariagrechishnikova/molecule_structure_generation#1]
Hi Daria. Thanks for sharing the code with the drug design community! 
In your associated article from Scientific Reports, there are a few ROC-AUC curves provided for evaluating the discriminating ability of SMINA docking software. 
I had a few questions regarding how the thresholding works and what are the class labels for the datasets compared in the figures. It would be really useful if you can share the scripts for the curve calculation from docking scores or if you can explain how the curves are plotted from the docking scores along with the associated hypotheses.

**Comment by dariagrechishnikova** [comment]
Hello! Here we consider SMINA as a classifier able to distinguish between binders and non-binders. We used scores output by SMINA to plot ROC curves.  So the thresholds here are just score values separating compounds to binders and non-binders. At first, we checked that it confidently separates molecules that are known to bind with the protein of interest from the randomly chosen compounds (we consider them as non-binders). Then we perform this procedure for generating compounds vs randomly chosen and also for other groups.
