### ISSUE TITLE
Fix dependency versions

### ISSUE THREAD

**Issue by AndreasBergmeister** [dariagrechishnikova/molecule_structure_generation#2]
I tried to replicate the code, but with the current versions of the used libraries, there are a lot of incompatibility issues. 
Could you please fix the version of the dependencies in the code, such that it is possible to run it.

Eg. 
"pip install tensor2tensor==1.15.7" instead of "pip install tensor2tensor"

**Comment by mshik** [comment]
Hi, I'm facing similar dependency issues. Were you able to resolve the issues? Please comment the solution.

**Comment by mshik** [comment]
> I tried to replicate the code, but with the current versions of the used libraries, there are a lot of incompatibility issues.
> Could you please fix the version of the dependencies in the code, such that it is possible to run it.
> 
> Eg.
> "pip install tensor2tensor==1.15.7" instead of "pip install tensor2tensor"

Hi, I'm facing similar dependency issues. Were you able to resolve the issues? Please comment the solution if yes.

**Comment by dariagrechishnikova** [comment]
I fixed model_training_and_decoding notebook to be compatible with tf 2.6 and run it. Also I added a file with requirements.
